# Generated by Django 4.2.2 on 2023-07-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='organization',
            new_name='canteen',
        ),
    ]
