# Generated by Django 4.2.2 on 2023-07-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_organization_meal_canteen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='canteen',
        ),
    ]
