# Generated by Django 4.2.2 on 2023-07-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cart_completedorderhistory_remove_order_canteen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
    ]
