# Generated by Django 4.2.2 on 2023-07-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_organization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AlterUniqueTogether(
            name='completedorderhistoryitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='completedorderhistoryitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='completedorderhistoryitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='completedorderhistoryitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.meal'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('meal', 'user')},
        ),
        migrations.DeleteModel(
            name='CompletedOrderHistory',
        ),
        migrations.DeleteModel(
            name='CompletedOrderHistoryItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='+', to='base.cartitem'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
