# Generated by Django 4.2.2 on 2023-07-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
