# Generated by Django 4.2.2 on 2023-07-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_cartitem_user_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
    ]
