# Generated by Django 4.2.2 on 2023-07-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_completedorderitems_completedorders_order_ordersitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedOrders',
            new_name='CompletedOrder',
        ),
        migrations.RenameModel(
            old_name='CompletedOrderItems',
            new_name='CompletedOrderItem',
        ),
        migrations.RenameModel(
            old_name='OrdersItem',
            new_name='OrderItem',
        ),
    ]
