# Generated by Django 4.2.2 on 2023-07-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_completedorderitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='canteen',
        ),
    ]
