# Generated by Django 4.2.2 on 2023-07-06 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_order_canteen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_canteen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_canteen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_meals',
        ),
        migrations.AddField(
            model_name='user',
            name='isprovider',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.canteen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('default_canteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.canteen')),
                ('favourite_canteen', models.ManyToManyField(blank=True, related_name='+', to='base.canteen')),
                ('favourite_meals', models.ManyToManyField(blank=True, related_name='+', to='base.meal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
