# Generated by Django 4.2.2 on 2023-08-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_canteen_canteen_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isprovider',
        ),
    ]
