# Generated by Django 4.2.2 on 2024-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_order_time_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='qunatity_prepared',
            field=models.IntegerField(default=0),
        ),
    ]
