# Generated by Django 4.2.2 on 2024-01-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_meal_qunatity_prepared'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='otp',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
