# Generated by Django 4.2.2 on 2024-09-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_canteen_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.meal')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReceiveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_requested', models.DateTimeField(auto_now_add=True)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=4)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.canteen')),
                ('receivedItems', models.ManyToManyField(to='base.receiveditem')),
            ],
        ),
    ]
